steps:
  - label: ":hammer: Tests"
    plugins:
      - docker-compose#v4.10.1:
          run: tests
  # - label: ":sparkles: Lint"
  #   plugins:
  #     - plugin-linter#v3.1.0:
  #         id: minutebook/commitlint
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**/*

  - label: ":github: Release"
    command: "npm i; npx -y semantic-release"
    branches: "main"
    plugins:
      - docker#v5.7.0:
          image: "node:20"