steps:
  - label: ":hammer: Tests"
    plugins:
      - docker-compose#v4.10.1:
          run: tests
  # - label: ":sparkles: Lint"
  #   plugins:
  #     - plugin-linter#v3.1.0:
  #         id: minutebook/commitlint
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**/*

  - wait

  - label: ":github: Release"
    command: "npx -y semantic-release"
    branches: "main"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            GITHUB_TOKEN:
              secret-id: "mb-buildkite-default-secret"
              json-key: ".BUILDKITE_PLUGIN_COMMITLINT_GITHUB_TOKEN"
      - docker#v5.7.0:
          image: "node:20"
          environment:
            - "GITHUB_TOKEN"
            - "CI"