#!/bin/bash
set -euo pipefail

fail() {
    printf '%s\n' "$1" >&2
    exit "${2-1}"
}

debug() {
    [ -z ${BUILDKITE_PLUGIN_COMMITLINT_DEBUG+x} ] || echo "[DEBUG] : $*" >&2
}

apt-get -qq update && apt-get -qq -y --no-install-recommends install jq

owner=$(echo "${BUILDKITE_REPO#git@github.com:}" | cut -d '/' -f1)
debug "Repository owner: $owner"
repo=$(echo "${BUILDKITE_REPO#git@github.com:}" | cut -d '/' -f2 | cut -d '.' -f1)
debug "Repository name: $repo"

debug "Pull request number: $BUILDKITE_PULL_REQUEST"

debug "Pull request commit list: https://api.github.com/repos/$owner/$repo/pulls/$BUILDKITE_PULL_REQUEST/commits"

commits=$(curl -Ls \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $BUILDKITE_PLUGIN_COMMITLINT_GITHUB_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/repos/$owner/$repo/pulls/$BUILDKITE_PULL_REQUEST/commits") || exit $?

error=$(echo "$commits" | jq -r 'type')
if [ $error != "array" ]; then
    fail "Unexpected payload: $commits"
fi

debug "Commits: $commits"

count=$(echo "$commits" | jq -r '. | length')
debug "Commit count: $count"

test -f "package.json" && npm install
git config --global --add safe.directory /workdir

echo
debug "Linting commit from: HEAD~$count"
npx -y commitlint --from HEAD~"$count"
