#!/bin/bash
set -euo pipefail

git_mirror_path="/var/lib/buildkite-agent/git-mirrors"
hooks=$(dirname "${BASH_SOURCE[0]}")

debug() {
    [ -z ${BUILDKITE_PLUGIN_COMMITLINT_DEBUG+x} ] || echo "[DEBUG] : $*" >&2
}

info() {
    echo "[INFO] : $*"
}

main() {
    if [[ -z "${BUILDKITE_PLUGIN_COMMITLINT_GITHUB_TOKEN}" ]]; then
        info "Missing GitHub access token"
        exit 1
    fi

    if [[ -z "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}" ]]; then
        info "No Pull Request detected"
        info "Skipping Commitlint plugin as it is only intended to run against Pull Request builds"
        exit 0
    fi

    NODE_VERSION=${BUILDKITE_PLUGIN_COMMITLINT_NODE_VERSION:-"20"}

    info "Plugin command absolute directory name: $hooks"
    info "Current directory: $(pwd)"

    ###
    # Get commit count & run commitlint
    ###
    docker run \
        -e BUILDKITE_REPO \
        -e BUILDKITE_PULL_REQUEST \
        -e BUILDKITE_PLUGIN_COMMITLINT_GITHUB_TOKEN \
        -e BUILDKITE_PLUGIN_COMMITLINT_DEBUG \
        --label "com.buildkite.job-id=${BUILDKITE_JOB_ID}" \
        --workdir=/workdir \
        --volume="$git_mirror_path:$git_mirror_path" \
        --volume="$(pwd)":/workdir \
        --volume="$hooks":/hooks \
        -it \
        --rm \
        public.ecr.aws/docker/library/node:"$NODE_VERSION" \
        /bin/bash -c "/hooks/scripts/commitlint"
}

main "$@"
